### ISSUE TITLE
random crash?

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#136]
Just saw this when I began connecting to a Flutter. The spinner went for less than a second before the app hard-crashed back to the home screen and spit this out in the console:
```
04-06 14:14:48.356 10208-10208/? E/WindowManager: android.view.WindowLeaked: Activity org.cmucreatelab.flutter_android.activities.AppLandingActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{29bcfc22 V.E..... R......D 0,0-563,162} that was originally added here
                                                      at android.view.ViewRootImpl.<init>(ViewRootImpl.java:385)
                                                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
                                                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:87)
                                                      at android.app.Dialog.show(Dialog.java:332)
                                                      at org.cmucreatelab.flutter_android.helpers.SessionHandler.createProgressDialog(SessionHandler.java:40)
                                                      at org.cmucreatelab.flutter_android.helpers.SessionHandler.startSession(SessionHandler.java:66)
                                                      at org.cmucreatelab.flutter_android.activities.AppLandingActivity$5.onItemClick(AppLandingActivity.java:206)
                                                      at android.widget.AdapterView.performItemClick(AdapterView.java:305)
                                                      at android.widget.AbsListView.performItemClick(AbsListView.java:1166)
                                                      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3073)
                                                      at android.widget.AbsListView$3.run(AbsListView.java:3870)
                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                      at android.os.Looper.loop(Looper.java:135)
                                                      at android.app.ActivityThread.main(ActivityThread.java:5484)
                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
04-06 14:14:49.415 10208-10208/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.cmucreatelab.flutter_android, PID: 10208
                                                   java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{29bcfc22 V.E..... R......D 0,0-563,162} not attached to window manager
                                                       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
                                                       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
                                                       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:123)
                                                       at android.app.Dialog.dismissDialog(Dialog.java:382)
                                                       at android.app.Dialog.dismiss(Dialog.java:365)
                                                       at org.cmucreatelab.flutter_android.helpers.SessionHandler.createProgressDialog(SessionHandler.java:34)
                                                       at org.cmucreatelab.flutter_android.helpers.SessionHandler.startSession(SessionHandler.java:66)
                                                       at org.cmucreatelab.flutter_android.activities.AppLandingActivity$5.onItemClick(AppLandingActivity.java:206)
                                                       at android.widget.AdapterView.performItemClick(AdapterView.java:305)
                                                       at android.widget.AbsListView.performItemClick(AbsListView.java:1166)
                                                       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3073)
                                                       at android.widget.AbsListView$3.run(AbsListView.java:3870)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5484)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by tasota** [comment]
also code was around commit f1922371d168746c1d2269fa9e3d5236fa75e673

**Comment by pdille** [comment]
I had this happen to me more than once in the last few days. You can fairly consistently reproduce it if you minimize and reopen the app while connecting. This appears to be a regression of #111
