### ISSUE TITLE
java.lang.NumberFormatException when trying to connect flutter (DataLoggingHandler)

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#41]
introduced in commit 2a8a48e7918ec8eb9331f523415b6494b7f7694a

console output:
```
12-26 11:45:06.472 12432-12444/org.cmucreatelab.flutter_android D/FlutterAndroid: onMessageReceived - P,4294967295,4290
12-26 11:45:06.472 12432-12444/org.cmucreatelab.flutter_android D/FlutterAndroid: Read Number of Points response
12-26 11:45:06.474 12432-12444/org.cmucreatelab.flutter_android W/BluetoothGatt: Unhandled exception in callback
                                                                                 java.lang.NumberFormatException: Invalid int: "4294967295"
                                                                                     at java.lang.Integer.invalidInt(Integer.java:138)
                                                                                     at java.lang.Integer.parse(Integer.java:413)
                                                                                     at java.lang.Integer.parseInt(Integer.java:367)
                                                                                     at java.lang.Integer.parseInt(Integer.java:334)
                                                                                     at java.lang.Integer.valueOf(Integer.java:525)
                                                                                     at org.cmucreatelab.flutter_android.helpers.DataLoggingHandler.readNumberOfPoints(DataLoggingHandler.java:92)
                                                                                     at org.cmucreatelab.flutter_android.helpers.DataLoggingHandler.onMessageReceived(DataLoggingHandler.java:192)
                                                                                     at org.cmucreatelab.flutter_android.helpers.SessionHandler$3.onReceived(SessionHandler.java:126)
                                                                                     at com.bluecreation.melodysmart.DataService$1.onCharacteristicChanged(DataService.java:40)
                                                                                     at com.bluecreation.melodysmart.BluetoothLeService$2.onCharacteristicChanged(BluetoothLeService.java:224)
                                                                                     at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:438)
                                                                                     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:399)
                                                                                     at android.os.Binder.execTransact(Binder.java:461)
```

**Comment by tasota** [comment]
Even when checking for bad response format (notice there are only 3 values in that response, but there should be 4; missing the isLogging flag) the code seems to currently rely on parsing something to continue on to the next activity. I tried faking this with a call to `listener.onDataSetPopulated()` from `FlutterOG` but it still wasn't happy.

**Comment by tasota** [comment]
I believe this was fixed with a firmware update
